package API.Controllers;
//

import API.Models.MStudent;
import API.Repositories.StudentRepository;
import API.jwt.JwtTokenUtil;
import API.jwt.JwtUserDetails;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;


@Controller	// This means that this class is a Controller
@RequestMapping(path="/student") // This means URL's start with /student (after Application path)
public class StudentController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private StudentRepository studentRepository;

	@Autowired
	private BCryptPasswordEncoder bCryptPasswordEncoder;

	@Autowired
	private UserDetailsService jwtUserDetailsService;

	@Autowired
	private JwtTokenUtil jwtTokenUtil;

	@PostMapping(path="/create") // Map ONLY POST Requests
	public @ResponseBody HashMap<String, String> addNewStudent (@RequestHeader("Authorization")String requestTokenHeader, @RequestBody MStudent mStudent) {
		HashMap<String , String> responseMessage = new HashMap<>();
		if (checkAuth(new String[] {"admin"} ,requestTokenHeader)) {
			if (MStudent.choicefields(mStudent)) {
				String encodedPassword = bCryptPasswordEncoder.encode(mStudent.getPassword());
				mStudent.setPassword(encodedPassword);
				studentRepository.save(mStudent);
				responseMessage.put("Success","Created a new student");
				return responseMessage;
			}
			responseMessage.put("Error","Some fields are missing");
			return responseMessage;
		}
		responseMessage.put("Error","You do not have the privileges for this action" );
		return responseMessage;
	}

	@GetMapping(path="/")
	public @ResponseBody HashMap<String, Object> getAllStudents(@RequestHeader("Authorization") String requestTokenHeader) {

		HashMap<String , Object> responseMessage = new HashMap<>();
		if (checkAuth(new String[]{"admin", "teacher"} , requestTokenHeader)) {
			responseMessage.put("Success", studentRepository.findAll());
			return responseMessage;
		}
		responseMessage.put("Error","You do not have the privileges for this action" );
		return responseMessage;
	}

	public boolean checkAuth(String[] roles, String requestTokenHeader) {
		String jwtToken = requestTokenHeader.substring(7);
		String username = jwtTokenUtil.getUsernameFromToken(jwtToken);

		JwtUserDetails userDetails = (JwtUserDetails) this.jwtUserDetailsService.loadUserByUsername(username);

		for (int num1 = 0  ; num1 < roles.length; num1++ ) {
			if (roles[num1].equals(userDetails.getRole())) {
				return true;
			}
		}
		return  false;
	}
}
