package API.Controllers;
//

import API.Models.MStudent;
import API.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;
import java.util.UUID;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/student") // This means URL's start with /student (after Application path)
public class StudentController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private StudentRepository studentRepository;

	@PostMapping(path="/") // Map ONLY POST Requests
	public @ResponseBody String addNewStudent (@RequestBody MStudent MStudent) {
		if (MStudent.choicefields(MStudent)) {
			studentRepository.save(MStudent);
			return "created a new student";
		}
		return  "some fields are missing";
	}

	@GetMapping(path="/")
	public @ResponseBody Iterable<MStudent> getAllStudents() {
		return studentRepository.findAll();
	}
	@GetMapping(path = "{id}")
	public @ResponseBody
	Optional<MStudent> getStudentById(@PathVariable("id")UUID id) {
		return studentRepository.findById(id);
	}
}
